[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"


[[headers]]
  for = "/images/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=604800"
