[build]
  command = "npm run build"
  publish = ".next"

[images]
	remote_images = ["https://content.timothysykes.com/wp-content/uploads/.*"]

[[plugins]]
  package = "netlify-plugin-cypress"

[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "max-age=31536123, public"

[[headers]]
for = "/images/*.svg"
[headers.values]
Cache-Control = "max-age=31536000, public"

[[headers]]
for = "/images/*.webp"
[headers.values]
Cache-Control = "max-age=31536000, public"

[[headers]]
for = "/images/*.gif"
[headers.values]
Cache-Control = "max-age=31536000, public"

[[headers]]
for = "/images/*.jpg"
[headers.values]
Cache-Control = "max-age=31536000, public"

[[headers]]
for = "/images/*.png"
[headers.values]
Cache-Control = "max-age=31536000, public"

[[headers]]
for = "/images/assets/*.webp"
[headers.values]
Cache-Control = "max-age=31536000, public"

[[headers]]
for = "/images/assets/*.svg"
[headers.values]
Cache-Control = "max-age=31536000, public"

[[headers]]
for = "/images/authorsPics/*.webp"
[headers.values]
Cache-Control = "max-age=31536000, public"

[[headers]]
for = "/images/icons/*.svg"
[headers.values]
Cache-Control = "max-age=31536000, public"

[[headers]]
for = "/_nuxt/*.svg"
[headers.values]
Cache-Control = "max-age=31536000, public"

[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "max-age=31536000, public"

